on:
  push:
    branches:
      - master
jobs:
  docker-compose:
    runs-on: self-hosted
    environment: docker
    steps:
    - name: Checkout code
      uses: actions/checkout@v2 
 
    - name: Run Docker compose command
      env:
        MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        MYSQL_SCHEMA: ${{ secrets.MYSQL_SCHEMA }}
        MYSQL_HOST: ${{ vars.MYSQL_HOST }}
        MYSQL_PORT: ${{ vars.MYSQL_PORT }}
        PORT: ${{ vars.PORT }}
      run: docker compose -f docker/github-compose.yaml -p koidos-server up --build -d 
 
  
